import fs from "fs";
import path from "path";

export default class DailySessionSummarizer {
  async run(context) {
    const { date, paths, logger } = context;

    const transcript = this.safeLoad(paths.transcript);

    const summary = `
# Daily Session Summary — ${date}

## High-Level Summary
This is a test summary generated by the Daily Session Summarizer.

## Key Decisions
None recorded.

## Technical Actions
None recorded.

## Blockers
None recorded.

## Next Steps
None recorded.

## Alignment with Goals/SOPs
None recorded.
`;

    const outPath = path.join("logs", "sessions", `${date}.md`);
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, summary.trim(), "utf-8");

    logger.success(`Session summary written to: ${outPath}`);

    // Visible output for YOU
    console.log("Daily Session Summarizer executed.");
    console.log("Summary path:", outPath);

    return { sessionSummaryPath: outPath };
  }

  safeLoad(filePath) {
    try {
      if (!filePath || !fs.existsSync(filePath)) return "";
      return fs.readFileSync(filePath, "utf-8");
    } catch {
      return "";
    }
  }
}
